export const INCOME_TYPES = {
  SALARY: "SALARY",
  PERK: "PERKS",
  INTEREST_INCOME: "INTEREST INCOME",
};
export const EXPENSE_TYPES = {
  LOAN: "LOAN",
  PERSONAL_EXPENSE: "PERSONAL EXPENSE",
  INVESTMENT: "INVESTMENT",
};
