export const AUTH = {
  LOGGED_IN: 'LOGGED_IN',
} as const

export const BUDGET_QUERY_KEYS = {
  BUDGETS: 'BUDGETS',
} as const

export const TAGS = {
  TAGS: 'TAGS',
} as const

export const EXPENSES = {
  EXPENSES: 'EXPENSES',
  WEEKLY_EXPENSES: 'WEEKLY_EXPENSES',
  MONTHLY_EXPENSES: 'MONTHLY_EXPENSES',
  DATE_RANGE: 'DATE_RANGE',
} as const

export const INCOME_STATEMENT = {
  INCOME_STATEMENT: 'INCOME_STATEMENT',
  SOURCES: 'SOURCES',
  IS_EXPENSES: 'IS_EXPENSES',
} as const

export const BALANCE_SHEET = {
  ASSETS: 'ASSETS',
  LIABILITIES: 'LIABILITIES',
  LOAN_TRANSACTIONS: 'LOAN_TRANSACTIONS',
  LOANS_OVERVIEW: 'LOANS_OVERVIEW',
} as const

export const GOALS = {
  GOALS: 'GOALS',
  PROGRESS: 'PROGRESS',
  DETAILS: 'DETAILS',
  TIMELINE: 'TIMELINE',
} as const
