export const AUTH = {
  LOGGED_IN: 'LOGGED_IN',
} as const

export const BUDGET_QUERY_KEYS = {
  BUDGETS: 'BUDGETS',
} as const

export const TAGS = {
  TAGS: 'TAGS',
} as const

export const EXPENSES = {
  EXPENSES: 'EXPENSES',
  WEEKLY_EXPENSES: 'WEEKLY_EXPENSES',
  MONTHLY_EXPENSES: 'MONTHLY_EXPENSES',
  DATE_RANGE: 'DATE_RANGE',
} as const

export const EXPENSES_SEARCH = {
  EXPENSES_SEARCH: 'EXPENSES_SEARCH',
} as const

export const INCOME_STATEMENT = {
  INCOME_STATEMENT: 'INCOME_STATEMENT',
  SOURCES: 'SOURCES',
  IS_EXPENSES: 'IS_EXPENSES',
  INCOME_TYPE: 'INCOME_TYPE'
} as const

export const BALANCE_SHEET = {
  ASSETS: 'ASSETS',
  LIABILITIES: 'LIABILITIES',
  LOAN_TRANSACTIONS: 'LOAN_TRANSACTIONS',
  LOANS_OVERVIEW: 'LOANS_OVERVIEW',
} as const

export const GOALS = {
  GOALS: 'GOALS',
  GOAL: 'GOAL',
  PROGRESS: 'PROGRESS',
  DETAILS: 'DETAILS',
  TIMELINE: 'TIMELINE',
  GOAL_PROPORATIONALITY_TYPES: 'GOAL_PROPORATIONALITY_TYPES',
  KPI_TYPES: 'KPI_TYPES',
} as const

export const NOTIFICATION = {
  NOTIFICATION: 'NOTIFICATION'
} as const
