const Types = {
   STATUS_FEEDBACK:'STATUS_FEEDBACK',
   FETCH_EXPENSE: 'FETCH_EXPENSE',
   FETCH_BUDGET: 'FETCH_BUDGET',
   FETCH_WEEKLY_EXPENSE: 'FETCH_WEEKLY_EXPENSE',
   FETCH_MONTHLY_EXPENSE: 'FETCH_MONTHLY_EXPENSE',
   DELETE_EXPENSE: 'DELETE_EXPENSE',
   CREATE_EXPENSE: 'CREATE_EXPENSE',
   EDIT_EXPENSE: 'EDIT_EXPENSE',
   FETCH_TAGS: 'FETCH_TAGS',
   FETCH_GOAL:'FETCH_GOAL',
   DELETE_GOAL:'DELETE_GOAL',
   CREATE_GOAL:'CREATE_GOAL',
   EDIT_GOAL:'EDIT_GOAL',
   FETCH_ASSETS: 'FETCH_ASSETS',
   FETCH_LIABILITIES: 'FETCH_LIABILITIES',
   SET_INCOME_STATEMENT: 'SET_INCOME_STATEMENT'
};

export default Types;
