const Types = {
   FETCH_EXPENSE: 'FETCH_EXPENSE',
   FETCH_BUDGET: 'FETCH_BUDGET',
   FETCH_WEEKLY_EXPENSE: 'FETCH_WEEKLY_EXPENSE',
   FETCH_MONTHLY_EXPENSE: 'FETCH_MONTHLY_EXPENSE',
   DELETE_EXPENSE: 'DELETE_EXPENSE',
   CREATE_EXPENSE: 'CREATE_EXPENSE',
   EDIT_EXPENSE: 'EDIT_EXPENSE',
   FETCH_TAGS: 'FETCH_TAGS',
   FETCH_ASSETS: 'FETCH_ASSETS',
   FETCH_LIABILITIES: 'FETCH_LIABILITIES',
};

export default Types;
