const Types = {
   FETCH_EXPENSE: 'FETCH_EXPENSE',
   FETCH_BUDGET: 'FETCH_BUDGET',
   FETCH_WEEKLY_EXPENSE: 'FETCH_WEEKLY_EXPENSE',
   FETCH_MONTHLY_EXPENSE: 'FETCH_MONTHLY_EXPENSE',
};

export default Types;
