name: Auto-update Dependabot PRs

on:
  push:
    branches:
      - main  # or any other branch you want to monitor

jobs:
  update-dependabot-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Dependabot PRs
        run: |
          # Fetch all pull requests
          for pr in $(gh pr list --json number,author -q '.[] | select(.author.login == "dependabot[bot]").number'); do
            gh pr checkout $pr
            git fetch origin main  # or the branch you want to rebase against
            git rebase origin/main
            git push --force-with-lease
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}